export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SEARCH_BOX_OPEN = "SEARCH_BOX_OPEN";
export const SEARCH_BOX_CLOSE = "SEARCH_BOX_CLOSE";
export const ON_SEARCH = "ON_SEARCH";
export const MOBILE_SEARCH_BOX_SHOW = "MOBILE_SEARCH_BOX_SHOW";
export const SEARCH_PANEL_OPEN = "SEARCH_PANEL_OPEN";
export const SEARCH_PANEL_CLOSE = "SEARCH_PANEL_CLOSE";

export const FETCH_DEVICES_REQUEST = 'FETCH_DEVICES_REQUEST';
export const FETCH_DEVICES_SUCCESS = 'FETCH_DEVICES_SUCCESS';
export const FETCH_DEVICES_FAILURE = 'FETCH_DEVICES_FAILURE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';